version: "3"
services:
  application:
    image: expense-management
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=faizu123
      - MYSQL_DATABASE=user_management
    volumes:
      - /data/mysql
networks:
  springboot-db-net:
